package main

import (
	"html/template"
	"log"
	"os"
	"os/exec"
	"strings"
)

const modulePath = "github.com/kaihendry/asaguard/internal/"

var packages = []string{
	"hooks",
	"mcps",
	"perms",
	"policy",
	"result",
	"scorer",
	"secrets",
	"settings",
	"siem",
	"transcripts",
	"updater",
}

const css = `
body{font-family:system-ui,sans-serif;max-width:780px;margin:2rem auto;padding:0 1.25rem;color:#111;line-height:1.6}
h1{margin-bottom:.15rem}
h2{margin-top:2rem;border-bottom:1px solid #e0e0e0;padding-bottom:.25rem}
nav{margin-bottom:1.5rem;font-size:.9rem}
p{margin:.75rem 0}
.lead{font-size:1.05rem;color:#333}
dl{margin:0}dt{font-weight:600;margin-top:1rem}dd{margin:.25rem 0 .5rem 1.25rem;color:#444}
a{color:#0066cc}footer{margin-top:3rem;font-size:.8rem;color:#888;border-top:1px solid #eee;padding-top:.75rem}
`

const pkgTmpl = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{{.Name}} — asaguard guard rails</title>
<style>{{.CSS}}</style>
</head>
<body>
<nav><a href="index.html">← all guard rails</a></nav>
<h1>{{.Name}}</h1>
{{range .Paras}}<p{{if .Lead}} class="lead"{{end}}>{{.Text}}</p>
{{end}}
<footer>Generated by <code>make docs</code> from <code>go doc</code> source comments.</footer>
</body>
</html>`

const idxTmpl = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>asaguard guard rails</title>
<style>{{.CSS}}</style>
</head>
<body>
<h1>asaguard guard rails</h1>
<p class="lead">Security guard rails for Claude Code. Each check runs against your local
configuration and recent session transcripts and contributes to an overall compliance score.</p>
<h2>Checks</h2>
<dl>
{{range .Packages}}<dt><a href="{{.Name}}.html">{{.Name}}</a></dt>
<dd>{{.Summary}}</dd>
{{end}}</dl>
<footer>Generated by <code>make docs</code> · run <code>asaguard check</code> to score your installation.</footer>
</body>
</html>`

type para struct {
	Text template.HTML
	Lead bool
}

type pkgData struct {
	Name  string
	CSS   template.CSS
	Paras []para
}

type idxEntry struct {
	Name    string
	Summary template.HTML
}

type idxData struct {
	CSS      template.CSS
	Packages []idxEntry
}

// packageDoc returns the prose description from `go doc <pkg>` — the block of
// lines between the `package` declaration line and the first exported symbol.
func packageDoc(pkg string) (string, error) {
	out, err := exec.Command("go", "doc", modulePath+pkg).CombinedOutput()
	return string(out), err
}

// parseDoc extracts the package-description paragraphs from go doc output,
// stopping before the first line that looks like an exported symbol declaration.
func parseDoc(raw string) []para {
	lines := strings.Split(raw, "\n")

	// Skip the first `package <name> // import "..."` line and any blank lines after it.
	start := 0
	for start < len(lines) {
		t := strings.TrimSpace(lines[start])
		if strings.HasPrefix(t, "package ") {
			start++
			break
		}
		start++
	}
	// skip leading blank lines after package declaration
	for start < len(lines) && strings.TrimSpace(lines[start]) == "" {
		start++
	}

	// Collect prose lines until we hit an exported symbol line.
	var prose []string
	for i := start; i < len(lines); i++ {
		t := strings.TrimSpace(lines[i])
		if isSymbolLine(t) {
			break
		}
		prose = append(prose, lines[i])
	}

	return groupParagraphs(prose)
}

// isSymbolLine returns true for lines that start an exported Go declaration.
func isSymbolLine(t string) bool {
	for _, kw := range []string{"func ", "type ", "var ", "const "} {
		if strings.HasPrefix(t, kw) {
			return true
		}
	}
	return false
}

// groupParagraphs splits prose lines on blank lines, producing one para per block.
// The first paragraph is marked as Lead.
func groupParagraphs(lines []string) []para {
	var paras []para
	var cur []string

	flush := func() {
		text := strings.TrimSpace(strings.Join(cur, " "))
		if text != "" {
			paras = append(paras, para{
				Text: template.HTML(template.HTMLEscapeString(text)),
				Lead: len(paras) == 0,
			})
		}
		cur = nil
	}

	for _, l := range lines {
		if strings.TrimSpace(l) == "" {
			flush()
		} else {
			cur = append(cur, strings.TrimSpace(l))
		}
	}
	flush()
	return paras
}

// firstSentence returns the text up to and including the first period.
func firstSentence(paras []para) template.HTML {
	if len(paras) == 0 {
		return ""
	}
	s := string(paras[0].Text)
	if i := strings.Index(s, ". "); i >= 0 {
		return template.HTML(s[:i+1])
	}
	return paras[0].Text
}

func ensureDocsDir() error {
	return os.MkdirAll("docs", 0755)
}

func main() {
	if err := ensureDocsDir(); err != nil {
		log.Fatalf("create docs dir: %v", err)
	}

	pkgTpl := template.Must(template.New("pkg").Parse(pkgTmpl))
	idxTpl := template.Must(template.New("idx").Parse(idxTmpl))

	sharedCSS := template.CSS(css)
	var index []idxEntry

	for _, pkg := range packages {
		raw, err := packageDoc(pkg)
		if err != nil {
			log.Printf("warning: go doc for %s: %v", pkg, err)
		}
		paras := parseDoc(raw)
		data := pkgData{Name: pkg, CSS: sharedCSS, Paras: paras}
		index = append(index, idxEntry{Name: pkg, Summary: firstSentence(paras)})

		f, err := os.Create("docs/" + pkg + ".html")
		if err != nil {
			log.Fatalf("create %s.html: %v", pkg, err)
		}
		if err := pkgTpl.Execute(f, data); err != nil {
			log.Fatalf("render %s.html: %v", pkg, err)
		}
		f.Close()
		log.Printf("wrote docs/%s.html", pkg)
	}

	f, err := os.Create("docs/index.html")
	if err != nil {
		log.Fatalf("create index.html: %v", err)
	}
	defer f.Close()
	if err := idxTpl.Execute(f, idxData{CSS: sharedCSS, Packages: index}); err != nil {
		log.Fatalf("render index.html: %v", err)
	}
	log.Println("wrote docs/index.html")
}
